version: '3.9'

services:
  angular-front-end:
    build: 
      context: ./angular-front-end
      target: build
    ports:
      - '{{ env.var.FRONT_END_PORT }}:8080'
    volumes:
      - ./angular-front-end:/usr/local/app
    restart: always  
    command: > 
      sh -c '{{ env.var.COMMAND }}'
  express-app:
    build: ./api
    environment:
      DB_NAME: '{{ env.var.DB_NAME }}' 
      HOST: mongodbengine
      MONGO_URL: mongodb://{{ env.var.MONGODB_ADMINUSERNAME }}:{{ env.var.MONGODB_ADMINPASSWORD }}@mongodbengine:27017
    volumes:
      - ./api:/app 
    ports:
      - '{{ env.var.API_PORT }}:12345'
    depends_on:
      - mongodbengine
    networks:
      - mynetwork

  mongodbengine:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: {{ env.var.MONGODB_ADMINUSERNAME }}
      MONGO_INITDB_ROOT_PASSWORD: {{ env.var.MONGODB_ADMINPASSWORD }}
    restart: always  
    volumes:
      - ./db/data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
        - mynetwork
    
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodbengine
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: {{ env.var.MONGO_BASICAUTH_USERNAME }} 
      ME_CONFIG_BASICAUTH_PASSWORD: {{ env.var.MONGO_BASICAUTH_PASSWORD }}
      ME_CONFIG_MONGODB_URL: mongodb://{{ env.var.MONGODB_ADMINUSERNAME }}:{{ env.var.MONGODB_ADMINPASSWORD }}@mongodbengine:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: {{ env.var.MONGODB_ADMINUSERNAME }}
      ME_CONFIG_MONGODB_ADMINPASSWORD: {{ env.var.MONGODB_ADMINPASSWORD }}
    networks:
      - mynetwork

networks:
  mynetwork:
