version: '3.9'

services:
  messagebus:
    image: rabbitmq:latest
    hostname: "messagebus"
    labels:
      - NAME="messagebus"
    ports:
      - '4360:4369'
      - '5671:5671'
      - '5672:5672'
      - '25672:25672'
      - '15671:15671'
      - '15672:15672'

  angular-front-end:
    build: 
      dockerfile: Dockerfile.prod
      context: ./angular-front-end
      target: build
    ports:
      - '80:8080'
    volumes:
      - ./angular-front-end:/usr/local/app
    restart: always  
  #  command: > 
  #    sh -c 'ng build --configuration=production;npx http-server -p 8080 -c-1 dist/angular-front-end'
  
  nginx-reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./angular-front-end/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - angular-front-end
    networks:
      - mynetwork
   
  express-app:
    build: ./api
    environment:
      DB_NAME: '{{ env.vars.DB_NAME }}' 
      HOST: mongodbengine
      MONGO_URL: mongodb://{{ env.vars.MONGODB_ADMINUSERNAME }}:{{ env.vars.MONGODB_ADMINPASSWORD }}@mongodbengine:27017
    volumes:
      - ./api:/app 
    ports:
      - '80:12345'
    depends_on:
      - mongodbengine
    networks:
      - mynetwork

  mongodbengine:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: '{{ env.vars.MONGODB_ADMINUSERNAME }}'
      MONGO_INITDB_ROOT_PASSWORD: '{{ env.vars.MONGODB_ADMINPASSWORD }}'
    restart: always  
    volumes:
      - ./db/data:/data/db
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
        - mynetwork
    
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodbengine
    restart: always
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: '{{ env.vars.MONGO_BASICAUTH_USERNAME }}'
      ME_CONFIG_BASICAUTH_PASSWORD: '{{ env.vars.MONGO_BASICAUTH_PASSWORD }}'
      ME_CONFIG_MONGODB_URL: mongodb://{{ env.vars.MONGODB_ADMINUSERNAME }}:{{ env.vars.MONGODB_ADMINPASSWORD }}@mongodbengine:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: '{{ env.vars.MONGODB_ADMINUSERNAME }}'
      ME_CONFIG_MONGODB_ADMINPASSWORD: '{{ env.vars.MONGODB_ADMINPASSWORD }}'
    networks:
      - mynetwork

networks:
  mynetwork:
